### ISSUE TITLE
[GH Request] Please create GitHub teams corresponding to 2U squads

### ISSUE THREAD

**Issue by nedbat** [openedx/axim-engineering#980]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Requested Change

@feanil 
We'd like to have GitHub teams that correspond to squads within 2U.  A yaml description of the team names and members is here:
```yaml
- team_name: 2u-aperture
  users:
  - MaxFrank13
  - cdeery
  - deborahgu
  - hurtstotouchfire
  - jsnwesson
  - justinhynes
- team_name: 2u-arbi-bom
  users:
  - UsamaSadiq
  - awais786
  - iamsobanjaved
  - irtazaakram
  - mumarkhan999
  - zubairshakoorarbisoft
- team_name: 2u-arch-bom
  users:
  - dianakhuang
  - jmbowman
  - nedbat
  - rgraber
  - robrap
  - timmc-edx
- team_name: 2u-aurora
  users:
  - Daniel-hershel
  - jansenk
  - jszewczulak
  - leangseu-edx
  - mattcarter
  - muselesscreator
  - nsprenkle
- team_name: 2u-cosmonauts
  users:
  - MichaelRoytman
  - Zacharis278
  - alangsto
  - chennighan2u
  - ilee2u
  - spencertiberi
  - varshamenon4
- team_name: 2u-fed-bom
  users:
  - BilalQamar95
  - Mashal-m
  - Syed-Ali-Abbas-Zaidi
  - abdullahwaheed
- team_name: 2u-infinity
  users:
  - AhtishamShahid
  - asadazam93
  - awais-ansari
  - ayesha-waris
  - ayub02
  - muhammadadeeltajamul
  - saadyousafarbi
  - sundasnoreen12
- team_name: 2u-kubrick
  users:
  - aethant
  - ashultz0
  - davidnuon
  - germanolleunlp
  - rijuma
- team_name: 2u-markhors
  users:
  - irfanuddinahmad
  - muhammad-ammar
  - saleem-latif
  - sameenfatima78
  - tahir-arbisoft
  - zamanafzal
- team_name: 2u-mobile
  users:
  - HamzaIsrar12
  - bilalawan321
  - farhan-arshad-dev
  - hassan6190
  - jawad-khan
  - memuzdak
  - miankhalid
  - moeez96
  - mumer92
  - omerhabib26
  - saeedbashir
- team_name: 2u-phoenix
  users:
  - Ali-D-Akbar
  - AliAdnanSohail
  - DawoudSheraz
  - ansabgillani
  - azanbinzahid
  - kashifch
  - uzairr
- team_name: 2u-purchase
  users:
  - HammadAhmadWaqas
  - colinbrash
  - grmartin
  - natabene
  - pshiu
  - wdrussell2015
  - zubair-ce07
- team_name: 2u-quokkas
  users:
  - alex-sheehan-edx
  - bcitro
  - johnnagro
  - kiram15
  - marlonkeating
- team_name: 2u-supernova
  users:
  - BrandonHBodine
  - Guilleves
  - Rodra
  - hajorg
- team_name: 2u-titans
  users:
  - adamstankiewicz
  - brobro10000
  - emrosarioa
  - iloveagent57
  - macdiesel
  - pwnage101
- team_name: 2u-tnl
  users:
  - KristinAoki
  - bszabo
  - cablaa77
  - connorhaugh
  - jesperhodge
  - kenclary
  - rayzhou-bit
  - theinkedkraken
- team_name: 2u-vanguards
  users:
  - ahtesham-quraish
  - attiyaIshaque
  - mubbsharanwar
  - syedsajjadkazmii
  - ugr3y
  - zainab-amir
```

### Reasoning

Eventually these will be used for reducing write access.
